name: finguard
description: "FinGuard - AI Legal Guardian for Financial Agreements"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.1.0
  file_picker: ^8.0.0+1
  google_fonts: ^6.2.0
  fl_chart: ^0.69.0
  animate_do: ^3.3.4
  shimmer: ^3.0.0
  firebase_core: ^4.4.0
  firebase_analytics: ^12.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
